### ISSUE TITLE
Error with update.sh

### ISSUE THREAD

**Issue by AZAkyla** [ASU-CompMethodsPhysics-PHY494/PHY494-assignments-skeleton#6]
After a fresh clone of my private repo I ran `./scripts/update.sh` per instructions in the README

```
$ ./scripts/update.sh
Adding remote repository 'skeleton'.
updating repository... git pull from skeleton
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 3), reused 8 (delta 3), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-assignments-skeleton
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> skeleton/master
Updating 6fde320..91ee890
error: unable to create file scripts/update.sh: Permission denied
creating subdirectories (if any are missing)
created assignment_01/Grade
created assignment_01/Submission
created assignment_01/Work
created assignment_02/Grade
created assignment_02/Submission
created assignment_02/Work
```

All of my assignments were populated, but the `update.sh` disappears.
@ianmkenney does not see the immediate issue with the script or permissions; do you see anything that could explain this @orbeckst ?

**Comment by orbeckst** [comment]
The error message says
> error: unable to create file scripts/update.sh: Permission denied

- Is this on Windows, Linux, of macOS?
- It *looks* as if there is a permission problem with the directory. Next steps depend on which operating system you are on.

**Comment by AZAkyla** [comment]
@orbeckst This is a Windows OS

**Comment by orbeckst** [comment]
Is it something like http://stackoverflow.com/questions/9200556/git-gives-me-a-permission-denied-error-when-writing-files-that-i-am-pulling – perhaps another program was accessing the file?

**Comment by orbeckst** [comment]
Then start looking through the hits of a Google search for [windows git pull permission denied](https://www.google.com/search?q=windows+git+pull+permission+denied&ie=utf-8&oe=utf-8).

**Comment by orbeckst** [comment]
Closing issue, no more comments.
