### ISSUE TITLE
Makeup Assignment Proposal

### ISSUE THREAD

**Issue by CalebMadsen** [ASU-CompMethodsPhysics-PHY494/PHY494-assignments-skeleton#7]
Hello, @orbeckst , I have submitted a proposal for a makeup assignment. I know I've only given myself a few days to complete it, but I think I should be able to do so, and some points are better than none. Please let me know if you would like to see anything more or less than what I've proposed.  

Thanks,
Caleb

**Comment by orbeckst** [comment]
Raise the issues in your own issue tracker – I am closing this one and continue ASU-CompMethodsPhysics-PHY494/assignments-2017-CalebMadsen#1
